### PR TITLE
[resource] add 'next-pool' field support to Pool

### LINKED ISSUE #23: Next-Pool field unable to be defaulted to 'none' on IP Pool creation
When adding support for IP Pools in PR #22 , I attempted to include the `next-pool` field. However, I ran into strange behavior that prevented me from supporting this field for the `pool` resource.

When creating an ip pool, the `next-pool` field is defaulted to 'none', whether that field is set to 'none' in a pool creation command or not. You can even query pools with the following command:  `:put [ find where next-pool!="none" ]` and you will have ids of pools that have no `next-pool` specified.

There was no issue including the `next-pool` field in the client side code. However, when included provider/acceptance testing, the `next-pool` field caused problems:

When registered in the provider schema, regardless of what `next-pool` was defaulted to, the following failing test output would be seen (this was with no assertion of what the `next-pool` value was):

```
=== RUN   TestAccMikrotikPool_create
    testing.go:684: Step 0 error: errors during apply:

        Error: from RouterOS device: input does not match any value of next-pool

          on /tmp/tf-test382668568/main.tf line 2:
          (source code not available)
```

However, if an assertion of what the value of `next-pool` should be was included in an acceptance test, regardless of what `next-pool` was defaulted to `none`, the value was seemingly ignored and an un-clean `terraform plan` is seen in the test output:

```
        DIFF:

        UPDATE: mikrotik_pool.bar
          comment:  "" => ""
          id:       "*97" => "*97"
          name:     "test-pool" => "test-pool"
          nextpool: "" => "none"
          ranges:   "172.16.0.1-172.16.0.8,172.16.0.10" => "172.16.0.1-172.16.0.8,172.16.0.10"



        STATE:

        mikrotik_pool.bar:
          ID = *97
          provider = provider.mikrotik
          comment =
          name = test-pool
          nextpool =
          ranges = 172.16.0.1-172.16.0.8,172.16.0.10
```

Some interesting links I have found:

See if the `unset` command can be used https://forum.mikrotik.com/viewtopic.php?t=32054 (I tried with no luck). A similar issue was reported in this Mikrotik thread https://forum.mikrotik.com/viewtopic.php?t=32054

### PR DESCRIPTION
**Pull request by maksym-nazarenko**
This PR adds support of `next-pool` field to the `pool` resource.
Closes #23

### CODE REVIEW

**Comment by maksym-nazarenko** [comment]
@ddelnano during investigation, I found that [client.Marshal()](https://github.com/ddelnano/terraform-provider-mikrotik/blob/80ec84a7d80fe5dc6c39aa2200f3fbc6e069c2fa/client/client.go#L254) func skips empty string so it is not possible to set any string value to an empty string via API.

File: mikrotik/resource_pool_test.go [hunk 1]
```diff
@@ -155,6 +189,22 @@ resource "mikrotik_pool" "bar" {
 `, name, ranges)
 }
 
+func testAccPoolWithNextPool(name, ranges, nextPoolToUse, nextPoolName string) string {
+	return fmt.Sprintf(`
+resource "mikrotik_pool" "bar" {
+    name = %q
+    ranges = %q
+	next_pool = %q
+	depends_on = [mikrotik_pool.next_pool]
```
Comment (ddelnano) [inline mikrotik/resource_pool_test.go:198]:
```suggestion
    next_pool = %q
    depends_on = [mikrotik_pool.next_pool]
```

**Comment by ddelnano** [comment]
@maksym-nazarenko apologies for the long delay on this. I was traveling and got engaged.

> during investigation, I found that [client.Marshal()](https://github.com/ddelnano/terraform-provider-mikrotik/blob/80ec84a7d80fe5dc6c39aa2200f3fbc6e069c2fa/client/client.go#L254) func skips empty string so it is not possible to set any string value to an empty string via API.

Regarding that, maybe the Marshal interface should allow something like `omitempty` like the json package provides? That would allow us to disambiguate a case like this, right?

I'll merge this for now, but I'd like to here your thoughts about the above.

**Comment by maksym-nazarenko** [comment]
> apologies for the long delay on this

no worries Dom, I found you work really useful so I'm happy to help you with enhancement of this provider

> I was traveling and got engaged

my congratulations to you 🎉 

> Regarding that, maybe the Marshal interface should allow something like omitempty like the json package provides? That would allow us to disambiguate a case like this, right?

yes, in theory, but sometimes you mean `omitempty` to skip this field entirely during `Update` and sometimes you want exactly `""` (empty string) to be set.
Frankly speaking, I have no good idea how to distinguish those to cases at the moment 🤷 
Anyway, let's keep it in mind when touch `Marshal` next time

**Comment by ddelnano** [comment]
I really appreciate your work on this and so just want to continue to make sure that my slow replies don't make you feel that the changes aren't appreciated! And thanks for the congratulations!

Yep, that makes sense and I agree we can keep that in mind for the future 👍
